//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHub_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BookingMedias = new HashSet<BookingMedia>();
            this.Bookings = new HashSet<Booking>();
            this.CatererBookings = new HashSet<CatererBooking>();
            this.halls = new HashSet<hall>();
            this.Media = new HashSet<Medium>();
        }
    
        public int U_id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> U_type { get; set; }
    
        public virtual ICollection<BookingMedia> BookingMedias { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<CatererBooking> CatererBookings { get; set; }
        public virtual ICollection<hall> halls { get; set; }
        public virtual ICollection<Medium> Media { get; set; }
    }
}
